---
- debug: msg="Using EnMasse git URL - {{ enmasse_git_url }}"

- include_tasks: "_download_enmasse_artifact.yml"

- name: Check EnMasse namespace for existing resources
  shell: oc get all -n {{ enmasse_namespace }}
  register: enmasse_resources_exist

- include_role:
    name: namespace
    tasks_from: create
  vars:
    name: "{{ enmasse_namespace }}"
    display_name: "AMQ Online"
    monitor: true
    is_service: true


- include_tasks: "_install_enmasse_from_artifact.yml"

- name: "Verify EnMasse deployment succeeded"
  shell: sleep 5; oc get pods --namespace {{ enmasse_namespace }}  |  grep  "deploy"
  register: result
  until: not result.stdout
  retries: 50
  delay: 10
  failed_when: result.stdout
  changed_when: False

- import_tasks: heimdall.yml
