---
- name: Apply resource overrides for codeready
  include_role:
    name: resource_limits
  vars:
    ns: "{{ che_namespace }}"
    resources: "{{ codeready_resources }}"
  when: (codeready_resources | d([], true) | length) > 0
