---

- include_role:
    name: namespace
    tasks_from: create
  vars:
    name: "{{ fuse_namespace }}"
    display_name: "Shared Fuse Online"
    monitor: true
    is_service: true

# Used to pull images from registry.redhat.io
- name: Expose vars
  include_vars: "../roles/imagestream_pull_secret/defaults/main.yml"

- name: Create shared fuse roles template
  template:
    src: roles.yaml
    dest: /tmp/shared-fuse-roles.yaml

- name: Apply shared fuse roles to cluster
  shell: "oc create -f /tmp/shared-fuse-roles.yaml -n {{ fuse_namespace }}"
  register: create_fuse_roles_cmd
  failed_when: create_fuse_roles_cmd.stderr != '' and 'AlreadyExists' not in create_fuse_roles_cmd.stderr

- name: "include rhsso vars"
  include_vars: ../../rhsso/defaults/main.yml

- name: Give role-binder role to customer-admin
  shell: "oc adm policy add-role-to-user role-binder {{ rhsso_evals_admin_username }} --role-namespace={{ fuse_namespace }} -n {{ fuse_namespace }}"

- include_role:
    name: imagestream_pull_secret
  vars:
    namespace: "{{ fuse_namespace }}"
    product_ns_pull_secret_name: "{{ fuse_pull_secret_name }}"

- name: Create Syndesis CRD
  shell: oc apply -f {{ fuse_online_crd_resources }}

- name: Create Fuse image streams
  shell: "oc replace --force -f {{ fuse_online_imagestream_resources }} -n openshift"
  register: fuse_create_imagestream
  failed_when: fuse_create_imagestream.stderr != '' and 'AlreadyExists' not in fuse_create_imagestream.stderr
  changed_when: fuse_create_imagestream.rc == 0

- name: Create fuse Operator resources in {{ fuse_namespace }}
  shell: oc apply -f {{ fuse_online_operator_resources }} -n {{ fuse_namespace }}

- name: TODO-REMOVE-THIS-AFTER-FUSE-ONLINE-INCLUDES-THESE-ARGS Patch args on operator to include monitoring resources addon
  shell: oc patch dc/syndesis-operator -p='{"spec":{"template":{"spec":{"containers":[{"name":"syndesis-operator","args":["-a","/conf/addons"]}]}}}}}' -n {{ fuse_namespace }}

- template:
    src: syndesis-customresource.yml.j2
    dest: /tmp/syndesis-customresource.yml

- name: Create Syndesis custom resource in {{ fuse_namespace }}
  shell: oc apply -f /tmp/syndesis-customresource.yml -n {{ fuse_namespace }}

- name: Verify Fuse deployment succeeded
  shell: oc get pods -n {{ fuse_namespace }} --selector="app=syndesis" -o jsonpath='{.items[*].status.containerStatuses[?(@.ready==true)].ready}' | wc -w
  register: fuse_verify_result
  until: fuse_verify_result.stdout.find("8") != -1
  retries: 50
  delay: 10
  changed_when: False

# Allow any authenticated user to access fuse. Sleep 5 to allow time for the
# new deployment to kick off.
- name: Remove OpenShift SAR configuration on Fuse Managed OAuth proxy
  shell: oc get dc syndesis-oauthproxy -o yaml -n {{ fuse_namespace }} | sed '/--openshift-sar/d' | oc apply -f - -n {{ fuse_namespace }}; sleep 5

- name: Verify Fuse deployment succeeded
  shell: oc get pods -n {{ fuse_namespace }} --selector="app=syndesis" -o jsonpath='{.items[*].status.containerStatuses[?(@.ready==true)].ready}' | wc -w
  register: fuse_verify_result
  until: fuse_verify_result.stdout.find("8") != -1
  retries: 50
  delay: 10
  changed_when: False

- name: Run Postinstall checks
  import_tasks: check_readiness.yml

- import_tasks: heimdall.yml
