---
msbroker_namespace: managed-service-broker
msbroker_image_org: quay.io/tremes
msbroker_image_tag: master
msbroker_git_ref: master
msbroker_template_url: "https://raw.githubusercontent.com/integr8ly/managed-service-broker/{{ msbroker_git_ref }}/templates/broker.template.yaml"
msbroker_clusterrole: managed-service
msbroker_clusterrolebinding: default-cluster-account-managed-service
msbroker_deployment_name: msb
msbroker_servicebroker_name: managed-service-broker
monitoring_key: middleware
required_crds:
  - "https://raw.githubusercontent.com/syndesisio/fuse-online-install/1.5/resources/syndesis-crd.yml"
