---
- hosts: master
  gather_facts: no
  tasks:
    - include_role:
        name: openshift
        tasks_from: set_master_vars
      when: run_master_tasks | default(true) | bool

# Required for Ansible Tower installs that need to login via oc as a prerequisite
- import_playbook: "../openshift.yml"

- hosts: localhost
  gather_facts: yes
  tasks:
    - include_role:
        name: prerequisites
        tasks_from: upgrade
      vars:
        from_versions:
          - "release-1.5.1"

- hosts: localhost
  gather_facts: yes
  tasks:
    # Monitoring upgrade
    - name: Expose monitoring vars
      include_vars: "../../roles/middleware_monitoring_config/defaults/main.yml"

    - name: Expose 3scale vars
      include_vars: "../../roles/3scale/defaults/main.yml"

    # Grafana
    - include_role:
        name: middleware_monitoring
        tasks_from: upgrade/grafana
      when: target_version.stdout == "release-1.5.1"

    # Prometheus & Alertmanager
    - include_role:
        name: middleware_monitoring
        tasks_from: upgrade/prometheus
      when: target_version.stdout == "release-1.5.1"

    # Pull the trigger on the monitoring upgrade
    - include_role:
        name: middleware_monitoring
        tasks_from: upgrade/trigger
      when: target_version.stdout == "release-1.5.1"
    # End monitoring upgrade

    - name: Recreate any CRs for alerts to ensure we have the latest
      include_role:
        name: middleware_monitoring_config
        tasks_from: upgrade.yml
      vars:
        mdc: false
        mobile_security_service: false
        ups: false

    - name: Apply latest backup monitoring alerts
      include_role:
        name: backup
        tasks_from: monitoring

    - name: Upgrade keycloak-operator
      include_role:
        name: rhsso
        tasks_from: upgrade.yaml

    - name: Upgrade keycloak-operator for user-sso
      include_role:
        name: rhsso-user
        tasks_from: upgrade.yaml

    # Heimdall
    - name: Update heimdall resources
      include_role:
        name: "{{ item }}"
        tasks_from: heimdall.yml
      with_items:
      - 3scale
      - apicurito
      - codeready
      - enmasse
      - fuse_managed
      - rhsso
      when: heimdall | default(true) | bool

- import_playbook: "../install_heimdall.yml"


#Update product version (should always be last)
- import_playbook: "../generate-customisation-inventory.yml"
- import_playbook: "../mobile_generate_manifest.yml"
